### ISSUE TITLE
关于“解”

### ISSUE THREAD

**Issue by denniscxc** [mathedu4all/bhcexam#1]
有的题目是求解，所以用\begin{solution}-“解：“ ,但有的题目是证明，这是用\begin{solution}似乎有点很准确。如何针对“证明题“用“证明：“或“证：”的词冠

**Comment by mathedu4all** [comment]
v1.0 版本solution环境，是出现一个解答框。并没有“解：”.

\method 命令显示带框关键词“解法一(二、三、...)”

\methodonly 命令显示带框关键词“解答”.

你可以登录www.mathcrowd.cn的卷库下载一份tex和编译好的教师版pdf看一下效果.
