### ISSUE TITLE
选择题选项中的`\ge`不会被替换为`\geqslant`

### ISSUE THREAD

**Issue by 1024th** [mathedu4all/bhcexam#12]
是否应该将 `\renewcommand` 放到 `\AtBeginDocument` 内？

**Comment by mathedu4all** [comment]
感谢提供建议，由于是公用宏包，我们认为保持尽可能少的自定义命令以适应尽可能多的场景. 你说的这个功能，目前橘子数学题库是在生成latex代码前实现的，就是说在题库下载的源码已经将\ge替换未\geqslant.

**Comment by mathedu4all** [comment]
我测试了下貌似能正常替换.
