### ISSUE TITLE
显示出的矩阵行列式是扁的

### ISSUE THREAD

**Issue by ZuoAoyu** [mathedu4all/bhcexam#13]
方矩，但显示时两边变扁了，或者说上下变宽了。

如图：![](https://img.xiake.me/roam/20220814190442.png)

**Comment by mathedu4all** [comment]
看不到图,不过大概率跟宏包无关.

**Comment by Explorer-cc** [comment]
此事是`ctex`故意为之，也许（我猜）在这个[issues](https://github.com/CTeX-org/ctex-kit/issues/549)里有记载....

@ZuoAoyu 但你连图都没传上来.....
