### ISSUE TITLE
如何修改默认字体为思源宋体？

### ISSUE THREAD

**Issue by yqzx0550** [mathedu4all/bhcexam#15]
如何修改默认字体为思源宋体？

**Comment by mathedu4all** [comment]
目前支持CTeX的fontset供选择,

https://github.com/mathedu4all/bhcexam/blob/13b22b895099d7edc136f9eff7cc4502ad1a12dc/BHCexam.cls#L45

具体设置可以参考CTeX文档 https://mirrors.cqu.edu.cn/CTAN/language/chinese/ctex/ctex.pdf

**Comment by Explorer-cc** [comment]
@yqzx0550 
具体来说，`fontset=ubuntu`就会自动调用`Note Serif CJK SC`(思源宋体)
