### ISSUE TITLE
在solution中不能调用figure，请问有何方法？

### ISSUE THREAD

**Issue by denniscxc** [mathedu4all/bhcexam#2]
I start with the following:
\begin{solution}
  \begin{figure}[htbp]
.......
 \end{figure}
\end{solution}
不能通过编译，但吧figure放在solution外面，就可以通过编译

**Comment by mathedu4all** [comment]
首先，需要下载最新的v1.0版宏包.

如果figure浮动环境不能用，可以用center环境.

你可以登录橘子数学网站，查看解析带图片的试题tex代码.

https://www.mathcrowd.cn/index.php?r=problem/view&id=JZqgb
