### ISSUE TITLE
win系统下make指令错误

### ISSUE THREAD

**Issue by ghost** [mathedu4all/bhcexam#4]
在win系统中cmd命令行中输入texdoc bhcexam，弹出窗口提示输入make *** 指令生成doc，但是win系统并没有提供make指令
![1](https://user-images.githubusercontent.com/31824476/71459892-8116c000-27e4-11ea-96bb-9c5df069681b.png)

**Comment by mathedu4all** [comment]
v0.4版本中文官方pdf文档可以在压缩包中找到. 

v1.0版本的文档看[这里](http://docs.mathcrowd.cn/zh_CN/latest/advances/bhcexam.html).
